apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubefirst-validation-local
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: atlantis-check
          path: validations/atlantis
          wave: '60'
        - name: vault-local-check
          path: validations/vault-local
          wave: '60'
  template:
      metadata:
        name: '{{name}}-demo'        
        annotations:
          argocd.argoproj.io/sync-wave: '{{wave}}'
      spec: 
        project: default
        source:
          path: '{{path}}'
          repoURL: https://github.com/6za/k1-watcher-demo.git
          targetRevision: HEAD
          directory:
            recurse: true # <--- Here
        destination:
          server: 'https://kubernetes.default.svc'
          namespace:  default
        syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
            retry:
              limit: 5
              backoff:
                duration: 5s
                maxDuration: 5m0s
                factor: 2  
