apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-gitlab-aws
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    deployments:
      - name: gitlab-webservice-default
        namespace: gitlab
        ready: "True"  
      - name: gitlab-toolbox
        namespace: gitlab
        ready: "True"  
      - name: gitlab-minio
        namespace: gitlab
        ready: "True"  
      - name: gitlab-kas
        namespace: gitlab
        ready: "True"                          
    statefulsets:
      - name: gitlab-postgresql
        namespace: gitlab
        ready: "True"        
      - name: gitlab-gitaly
        namespace: gitlab
        ready: "True"        
      - name: gitlab-postgresql
        namespace: gitlab
        ready: "True"                        
        
--- 
# Creates the argo annotation for CRD
apiVersion: batch/v1
kind: Job
metadata:
  name: run-post-gitlab-aws-ready-job
  namespace: argocd
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: portainer/kubectl-shell:latest
        command:
        - /bin/sh
        - -c
        - |
          #Do something          
          echo "post gitlab ready action"
          sleep 30
      restartPolicy: Never
  backoffLimit: 1   
