apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  name: wait-atlantis-local
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync    
spec:
    exit: 0
    timeout: 300
    pods:
      - name:  atlantis-0
        namespace:  atlantis
        phase: Running      
        labels:
          app: atlantis
        
--- 
# Creates the argo annotation for CRD
apiVersion: batch/v1
kind: Job
metadata:
  name: run-post-atlantis-ready-job
  namespace: argocd
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: portainer/kubectl-shell:latest
        command:
        - /bin/sh
        - -c
        - |
          #Do something          
          echo "post atlantis ready action"
          sleep 30
      restartPolicy: Never
  backoffLimit: 1   
