apiVersion: v1
kind: Pod
metadata:
  name:  my-app-01
  namespace:  my-app
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
